# ==========================================
# Stage 1: Install dependencies
# ==========================================
FROM node:20-alpine AS deps
WORKDIR /src/app

# Copy package files
COPY package.json package-lock.json ./
RUN npm install

# ==========================================
# Stage 2: Build the application
# ==========================================
FROM node:20-alpine AS builder
WORKDIR /src/app

COPY --from=deps /src/app/node_modules ./node_modules
COPY . .

# Disable Next.js telemetry during the build
ENV NEXT_TELEMETRY_DISABLED=1

# Build the Next.js app
RUN npm run build

# ==========================================
# Stage 3: Production server
# ==========================================
FROM node:20-alpine AS runner
WORKDIR /src/app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create a non-root user for security best practices
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy the public folder (static assets like images)
COPY --from=builder /src/app/public ./public

# Automatically leverage output traces to reduce image size
# Copy the standalone server and static files generated by Next.js
COPY --from=builder --chown=nextjs:nodejs /src/app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /src/app/.next/static ./.next/static

# Switch to the non-root user
USER nextjs

# Set the port and expose it
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# The standalone build outputs a standard Node.js server.js file
CMD ["node", "server.js"]